# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
# SPDX-License-Identifier: Apache-2.0
spring:
  jackson:
    default-property-inclusion: NON_NULL
  main:
    banner-mode: off
    web-application-type: reactive
  reactor:
    context-propagation: auto
  graphql:
    graphiql:
      enabled: true

server:
  port: 8080

arc:
  scripts:
    enabled: true
    folder: agents
    hotReload:
      enable: true
      delay: PT1S
  chat:
    ui:
      enabled: true
  subscriptions:
    events:
      enable: true

logging:
  level:
    root: WARN
    ai.ancf.lmos.arc: DEBUG
    ai.ancf.lmos.arc.app: WARN
    ArcDSL: DEBUG

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /
      exposure:
        include: prometheus,metrics,info,health
  endpoint:
    metrics:
      enabled: true
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true